### PR TITLE
Added high-res favicon, theme color for Android, style fixes.

### PR DESCRIPTION
**Pull request by hal7df**
-Added 192x192 favicon for web browsers capable of displaying high-res favicons.
-Added theme color for Chrome for Android 5.0+
-Made line spacing larger to ease reading.

### CODE REVIEW

**Comment by LG67** [comment]
so why em's instead of px?

**Comment by hal7df** [comment]
`em` is a multiple of the browser's default line height.

**Comment by LG67** [comment]
yes-but why do you choose ems instead of px?  How will the ems effect all
of font callouts that are given in px?

**Comment by hal7df** [comment]
I changed the `line-height` for the generic `body` and `h` tags. Any tag that derives its style from `body` will inherit the `line-height` setting, but if you override it then the new setting will apply over the old one. So, if you have a `p` that you gave a `line-height` of `60px`, then for that `p` the `line-height` attribute will be `60px`, not `1.2em`.

Using `em`s only apply to the attribute you're currently defining. If you use `px` elsewhere, it will be left untouched.

**Comment by hal7df** [comment]
Also, I edited my previous comment as I saw that it didn't give a good enough explanation of what I was trying to explain -- I think the answer to the former question was in that edit:

`em` is a multiple of the browser's default line height. Without any change to the line-height property, text will default to `1em`.

That way it's more cross-platform and scales depending on the browser.

**Pull request merged**
